# Generated by Django 2.2.10 on 2020-06-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200605_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='api.User'),
        ),
    ]
